# Copyright (c) 2024, 2026, Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl/

"""Idempotently create the Drive-Thru schema, seed data, and ORDS endpoints."""

import csv
import json
import os
from datetime import datetime, timedelta
from pathlib import Path

import oracledb


ROOT = Path(__file__).resolve().parent
WALLET_DIR = os.getenv("TNS_ADMIN", "/opt/fstech/wallet")
WALLET_PASSWORD = os.environ["ADB_WALLET_PASSWORD"]
ADMIN_PASSWORD = os.environ["ADB_ADMIN_PASSWORD"]
ADB_DSN = os.environ["ADB_DSN"]
APP_USER = "ADMIN"
STATUS_FILE = ROOT / "bootstrap-status.json"


def connect(user, password):
    return oracledb.connect(
        user=user,
        password=password,
        dsn=ADB_DSN,
        config_dir=WALLET_DIR,
        wallet_location=WALLET_DIR,
        wallet_password=WALLET_PASSWORD,
    )


def ignore_exists(cursor, statement):
    try:
        cursor.execute(statement)
    except oracledb.DatabaseError as exc:
        if exc.args[0].code != 955:
            raise


def create_tables(connection):
    cursor = connection.cursor()
    ignore_exists(cursor, """
        CREATE TABLE order_details (
            order_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 20000) PRIMARY KEY,
            registration_number VARCHAR2(32) NOT NULL,
            order_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            ordered_items CLOB NOT NULL,
            total_order_cost NUMBER(10,2) NOT NULL,
            customer_name VARCHAR2(200),
            weather_details VARCHAR2(1000)
        )
    """)
    ignore_exists(cursor, """
        CREATE INDEX order_details_registration_ix
        ON order_details (registration_number, order_date DESC)
    """)
    ignore_exists(cursor, """
        CREATE TABLE offers (
            offer_id VARCHAR2(32) PRIMARY KEY,
            offer_name VARCHAR2(200) NOT NULL,
            items_included VARCHAR2(1000) NOT NULL,
            regular_price NUMBER(10,2) NOT NULL,
            discounted_price NUMBER(10,2) NOT NULL,
            valid_until DATE
        )
    """)
    connection.commit()


def seed_orders(connection):
    rows = []
    with (ROOT / "seed" / "order_details.csv").open(newline="", encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            order_date = row["OrderDate"].strip().upper()
            if order_date.startswith("SYSDATE-"):
                order_date = datetime.now() - timedelta(
                    days=int(order_date.removeprefix("SYSDATE-"))
                )
            else:
                order_date = datetime.strptime(order_date, "%d/%m/%y")
            rows.append({
                "order_id": int(row["OrderID"]),
                "registration_number": row["RegistrationNumber"].strip().upper(),
                "order_date": order_date,
                "ordered_items": row["OrderedItems"],
                "total_order_cost": float(row["TotalOrderCost"]),
                "customer_name": row.get("Name", "").strip() or None,
            })
    connection.cursor().executemany("""
        MERGE INTO order_details target
        USING (
            SELECT :order_id order_id, :registration_number registration_number,
                   :order_date order_date, :ordered_items ordered_items,
                   :total_order_cost total_order_cost,
                   :customer_name customer_name
            FROM dual
        ) source
        ON (target.order_id = source.order_id)
        WHEN MATCHED THEN UPDATE SET
            target.registration_number = source.registration_number,
            target.order_date = source.order_date,
            target.ordered_items = source.ordered_items,
            target.total_order_cost = source.total_order_cost,
            target.customer_name = source.customer_name
        WHEN NOT MATCHED THEN INSERT (
            order_id, registration_number, order_date, ordered_items,
            total_order_cost, customer_name
        ) VALUES (
            source.order_id, source.registration_number, source.order_date,
            source.ordered_items, source.total_order_cost, source.customer_name
        )
    """, rows)
    connection.commit()


def seed_offers(connection):
    rows = []
    with (ROOT / "seed" / "offers.csv").open(newline="", encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            rows.append({
                "offer_id": row["OfferID"],
                "offer_name": row["OfferName"],
                "items_included": row["ItemsIncluded"],
                "regular_price": float(row["RegularPrice"]),
                "discounted_price": float(row["DiscountedPrice"]),
                "valid_until": datetime.strptime(row["ValidUntil"], "%d/%m/%y").date(),
            })
    connection.cursor().executemany("""
        MERGE INTO offers target
        USING (
            SELECT :offer_id offer_id, :offer_name offer_name,
                   :items_included items_included, :regular_price regular_price,
                   :discounted_price discounted_price, :valid_until valid_until
            FROM dual
        ) source
        ON (target.offer_id = source.offer_id)
        WHEN MATCHED THEN UPDATE SET
            target.offer_name = source.offer_name,
            target.items_included = source.items_included,
            target.regular_price = source.regular_price,
            target.discounted_price = source.discounted_price,
            target.valid_until = source.valid_until
        WHEN NOT MATCHED THEN INSERT (
            offer_id, offer_name, items_included, regular_price,
            discounted_price, valid_until
        ) VALUES (
            source.offer_id, source.offer_name, source.items_included,
            source.regular_price, source.discounted_price, source.valid_until
        )
    """, rows)
    connection.commit()


def configure_ords(connection):
    cursor = connection.cursor()
    cursor.execute("""
        BEGIN
          -- Autonomous Database provisions ADMIN as an enabled ORDS schema.
          -- Re-enabling it would alter the active mapping and raises ORA-20049.
          BEGIN
            ORDS.DELETE_MODULE(p_module_name => 'drive_thru');
          EXCEPTION WHEN OTHERS THEN NULL;
          END;
          ORDS.DEFINE_MODULE(
            p_module_name    => 'drive_thru',
            p_base_path      => 'api/',
            p_items_per_page => 50,
            p_status         => 'PUBLISHED'
          );

          ORDS.DEFINE_TEMPLATE('drive_thru', 'get_order_history');
          ORDS.DEFINE_HANDLER(
            p_module_name => 'drive_thru',
            p_pattern     => 'get_order_history',
            p_method      => 'GET',
            p_source_type => ORDS.SOURCE_TYPE_COLLECTION_FEED,
            p_source      => q'[
              SELECT order_id "orderid", order_date "orderdate",
                     ordered_items "ordereditems", total_order_cost "totalordercost",
                     customer_name "name", weather_details "weather_details"
              FROM order_details
              WHERE UPPER(registration_number) = UPPER(:registration_number)
              ORDER BY order_date DESC
            ]'
          );

          ORDS.DEFINE_TEMPLATE('drive_thru', 'search_offers');
          ORDS.DEFINE_HANDLER(
            p_module_name => 'drive_thru',
            p_pattern     => 'search_offers',
            p_method      => 'GET',
            p_source_type => ORDS.SOURCE_TYPE_COLLECTION_FEED,
            p_source      => q'[
              SELECT
                (SELECT MAX(DBMS_LOB.SUBSTR(ordered_items, 4000, 1)) KEEP
                        (DENSE_RANK FIRST ORDER BY order_date DESC)
                   FROM order_details
                  WHERE UPPER(registration_number) = UPPER(:registration_number)) "top_ordered_item",
                offer_name "recommended_offer", items_included "itemsincluded",
                regular_price "regularprice", discounted_price "discountedprice",
                valid_until "validuntil"
              FROM offers
              ORDER BY CASE WHEN EXISTS (
                SELECT 1 FROM order_details history
                WHERE UPPER(history.registration_number) = UPPER(:registration_number)
                  AND INSTR(UPPER(DBMS_LOB.SUBSTR(history.ordered_items, 4000, 1)),
                            UPPER(REGEXP_SUBSTR(items_included, '^[^,(]+'))) > 0
              ) THEN 0 ELSE 1 END, discounted_price
            ]'
          );

          ORDS.DEFINE_TEMPLATE('drive_thru', 'get_orders');
          ORDS.DEFINE_HANDLER(
            p_module_name => 'drive_thru',
            p_pattern     => 'get_orders',
            p_method      => 'GET',
            p_source_type => ORDS.SOURCE_TYPE_COLLECTION_FEED,
            p_source      => q'[
              SELECT order_id "orderid", registration_number "registrationnumber",
                     order_date "orderdate", ordered_items "ordereditems",
                     total_order_cost "totalordercost", customer_name "name",
                     weather_details "weather_details"
              FROM order_details
              ORDER BY order_date DESC
              FETCH FIRST 100 ROWS ONLY
            ]'
          );

          ORDS.DEFINE_TEMPLATE('drive_thru', 'insert_order');
          ORDS.DEFINE_HANDLER(
            p_module_name => 'drive_thru',
            p_pattern     => 'insert_order',
            p_method      => 'POST',
            p_source_type => ORDS.SOURCE_TYPE_PLSQL,
            p_source      => q'[
              DECLARE
                l_order_id order_details.order_id%TYPE;
              BEGIN
                INSERT INTO order_details (
                  registration_number, ordered_items, total_order_cost,
                  customer_name, weather_details
                ) VALUES (
                  :registration_number, :ordered_items, :total_cost,
                  :customer_name, :weather_details
                ) RETURNING order_id INTO l_order_id;
                OWA_UTIL.MIME_HEADER('application/json', FALSE);
                OWA_UTIL.HTTP_HEADER_CLOSE;
                HTP.PRN('{"status":"created","order_id":' || l_order_id || '}');
                :status_code := 201;
                COMMIT;
              END;
            ]'
          );
          COMMIT;
        END;
    """)
    connection.commit()


def main():
    # The stack is intentionally zero-touch: all application database objects
    # and ORDS metadata are owned by the pre-provisioned ADB ADMIN account.
    # This avoids creating or handing off an intermediate schema credential.
    with connect(APP_USER, ADMIN_PASSWORD) as connection:
        create_tables(connection)
        seed_orders(connection)
        seed_offers(connection)
        configure_ords(connection)
        cursor = connection.cursor()
        cursor.execute("SELECT COUNT(*) FROM order_details")
        order_rows = int(cursor.fetchone()[0])
        cursor.execute("SELECT COUNT(*) FROM offers")
        offer_rows = int(cursor.fetchone()[0])

    if order_rows < 2000 or offer_rows < 25:
        raise RuntimeError(
            f"Seed verification failed: order_details={order_rows}, offers={offer_rows}"
        )

    status = {
        "database": "ready",
        "schema": APP_USER,
        "order_rows": order_rows,
        "offer_rows": offer_rows,
        "ords_module": "drive_thru",
        "ords_base_path": "/ords/admin/api/",
        "ords_apis": {
            "insert_order": {
                "method": "POST",
                "path": "/ords/admin/api/insert_order",
            },
            "search_offers": {
                "method": "GET",
                "path": "/ords/admin/api/search_offers",
            },
            "get_order_history": {
                "method": "GET",
                "path": "/ords/admin/api/get_order_history",
            },
            "get_orders": {
                "method": "GET",
                "path": "/ords/admin/api/get_orders",
            },
        },
        "verified_at": datetime.now().astimezone().isoformat(),
    }
    STATUS_FILE.write_text(json.dumps(status, indent=2), encoding="utf-8")
    print(
        "Drive-Thru database, seed data, and ORDS endpoints are ready: "
        f"{order_rows} orders, {offer_rows} offers."
    )


if __name__ == "__main__":
    main()
